type Exercise {
  id: ID!
  name: String!,
  courseId: ID!,
  unitId: ID!,
  description: String,
  descriptionUrl: String
}

type Exercises {
  data: [Exercise]
  count: Int!
}

extend type Query {
  getExercise(id: ID!): Exercise
  listExercises(courseId: ID, unitId: ID): Exercises
  listValidExercises(courseId: ID!): Exercises
}

extend type Mutation {
  createExercise(name: String!, courseId: ID!, unitId: ID!): Exercise
  updateExercise(id: ID!, name: String!, courseId: ID!, unitId: ID!): Exercise
  updateExerciseDescriptionUrl(id: ID!, descriptionUrl: String!): Exercise
  disableExercise(id: ID!): Exercise
  deleteExercise(id: ID!): Response
}