type AssignedExam {
  id: ID!
  idNumber: ID!
  examTemplateId: ID!
  examTemplateName: String!
  created: String!
  courseId: ID!
  courseName: String!
}

type AssignedExams {
  data: [AssignedExam]
  count: Int!
}

extend type Query {
  listAssignedExams(idNumber: ID, courseId: ID): AssignedExams
}

extend type Mutation {
  createAssignedExam(examTemplateId: ID!, idNumber: ID!): AssignedExam
  deleteAssignedExam(id: ID!): Response
}