
type Course {
  id: ID!
  name: String
}

type Response {
  done: Boolean
}

type Query {
  getCourse(id: ID!): Course
  listCourses(q: String, offset: Int, limit: Int): [Course]
}

type Mutation {
  createCourse(name: String!): Course
  updateCourse(id: ID!, name: String!): Course
  deleteCourse(id: ID!): Response
}