type Course {
  id: ID!
  name: String
}

type Courses {
  data: [Course]
  count: Int!
}

extend type Query {
  getCourse(id: ID!): Course
  listCourses(name: String): Courses
}

extend type Mutation {
  createCourse(name: String!): Course
  updateCourse(id: ID!, name: String!): Course
  disableCourse(id: ID!): Course
  deleteCourse(id: ID!): Response
}